
CREATE ROLE MLFLOW_SPCS_ROLE 
GRANT ROLE MLFLOW_SPCS_ROLE TO USER MLFCTO_MAHDI
CREATE DATABASE MAHDI_PLAYGROUND
CREATE SCHEMA MLFLOW_TEST

USE DATABASE MAHDI_PLAYGROUND;
USE SCHEMA MLFLOW_TEST;

GRANT OWNERSHIP ON DATABASE MAHDI_PLAYGROUND TO ROLE MLFLOW_SPCS_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA MLFLOW_TEST TO ROLE MLFLOW_SPCS_ROLE COPY CURRENT GRANTS;

CREATE OR REPLACE WAREHOUSE MLFLOW_TEST WITH 
WAREHOUSE_SIZE = 'X-SMALL';

GRANT USAGE ON WAREHOUSE TEST TO ROLE MLFLOW_SERVICE_ROLE;

CREATE COMPUTE POOL IF NOT EXISTS MLFLOW_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS;

USE ROLE MLFLOW_SPCS_ROLE;

CREATE STAGE IF NOT EXISTS MLFLOW_STAGE
  ENCRYPTION = (TYPE='SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE);
  
CREATE OR REPLACE NETWORK RULE ALLOW_ALL_RULE
  TYPE = 'HOST_PORT'
  MODE = 'EGRESS'
  VALUE_LIST= ('0.0.0.0:443', '0.0.0.0:80');

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE  EXTERNAL ACCESS INTEGRATION ALLOW_ALL_EAI
  ALLOWED_NETWORK_RULES = (ALLOW_ALL_RULE)
  ENABLED = true;

GRANT USAGE ON INTEGRATION ALLOW_ALL_EAI TO ROLE MLFLOW_SPCS_ROLE;

CREATE OR REPLACE  IMAGE REPOSITORY MLFLOW_IMAGE;

GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE MLFLOW_SPCS_ROLE;

GRANT USAGE, MONITOR ON COMPUTE POOL MLFLOW_COMPUTE_POOL TO ROLE MLFLOW_SPCS_ROLE;
SHOW IMAGE REPOSITORIES IN SCHEMA MLFLOW_TEST;

USE ROLE MLFLOW_SPCS_ROLE;
CALL SYSTEM$REGISTRY_LIST_IMAGES('/MAHDI_PLAYGROUND/MLFLOW_TEST/MLFLOW_IMAGE');
USE ROLE MLFLOW_SPCS_ROLE;

CREATE SERVICE MAHDI_PLAYGROUND.MLFLOW_TEST.MLFLOW_SNOWPARK
IN COMPUTE POOL MLFLOW_COMPUTE_POOL
    FROM @MLFLOW_STAGE
    specification_file='mflowspec.yaml'
    external_access_integrations = (ALLOW_ALL_EAI);

DROP SERVICE MAHDI_PLAYGROUND.MLFLOW_TEST.MLFLOW_SNOWPARK
ALTER SERVICE MAHDI_PLAYGROUND.MLFLOW_TEST.MLFLOW_SNOWPARK SUSPEND
ALTER SERVICE MAHDI_PLAYGROUND.MLFLOW_TEST.MLFLOW_SNOWPARK RESUME
SHOW ENDPOINTS IN SERVICE MLFLOW_SNOWPARK;
DESCRIBE SERVICE MLFLOW_SNOWPARK

SELECT value AS log_line
  FROM TABLE(
    SPLIT_TO_TABLE(SYSTEM$GET_SERVICE_LOGS('MAHDI_PLAYGROUND.MLFLOW_TEST.MLFLOW_SNOWPARK', 0, 'mlflow'), '\n')
  )



